### ISSUE TITLE
Support for Serverside dart

### ISSUE THREAD

**Issue by arrrrny** [FirebaseExtended/firebase-dart#280] opened 2019-12-02 17:34 UTC
Is there a way to use this library on dart server side? I have a dart server application, and getting errors when I implemented this. It is not dart web, it is pure dart on angel framework.

 dart bin/dev.dart
../../.pub-cache/hosted/pub.dartlang.org/firebase-7.0.0/lib/src/top_level.dart:1:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
../../.pub-cache/hosted/pub.dartlang.org/firebase-7.0.0/lib/src/utils.dart:2:8: Error: Not found: 'dart:html'
import 'dart:html' show promiseToFuture;
       ^
../../.pub-cache/hosted/pub.dartlang.org/js-0.6.1+1/lib/js.dart:8:1: Error: Not found: 'dart:js'
export 'dart:js' show allowInterop, allowInteropCaptureThis;
^
../../.pub-cache/hosted/pub.dartlang.org/js-0.6.1+1/lib/js_util.dart:8:1: Error: Not found: 'dart:js_util'
export 'dart:js_util';
^
../../.pub-cache/hosted/pub.dartlang.org/firebase-7.0.0/lib/src/auth.dart:311:25: Error: The method 'allowInterop' isn't defined for the class 'Auth'.
 - 'Auth' is from 'package:firebase/src/auth.dart' ('../../.pub-cache/hosted/pub.dartlang.org/firebase-7.0.0/lib/src/auth.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
      var nextWrapper = allowInterop((firebase_interop.UserJsImpl user) {
                        ^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/firebase-7.0.0/lib/src/auth.dart:315:26: Error: The method 'allowInterop' isn't defined for the class 'Auth'.
 - 'Auth' is from 'package:firebase/src/auth.dart' ('../../.pub-cache/hosted/pub.dartlang.org/firebase-7.0.0/lib/src/auth.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
      var errorWrapper = allowInterop((e) => _changeController.addError(e));
                         ^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/firebase-7.0.0/lib/src/auth.dart:345:25: Error: The method 'allowInterop' isn't defined for the class 'Auth'.
 - 'Auth' is from 'package:firebase/src/auth.dart' ('../../.pub-cache/hosted/pub.dartlang.org/firebase-7.0.0/lib/src/auth.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
      var nextWrapper = allowInterop((firebase_interop.UserJsImpl user) {
                        ^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/firebase-7.0.0/lib/src/auth.dart:350:11: Error: The method 'allowInterop' isn't defined for the class 'Auth'.
 - 'Auth' is from 'package:firebase/src/auth.dart' ('../../.pub-cache/hosted/pub.dartlang.org/firebase-7.0.0/lib/src/auth.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
          allowInterop((e) => _idTokenChangedController.addError(e));
          ^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/firebase-7.0.0/lib/src/database.dart:164:9: Error: The method 'allowInterop' isn't defined for the class 'DatabaseReference<T>'.
 - 'DatabaseReference' is from 'package:firebase/src/database.dart' ('../../.pub-cache/hosted/pub.dartlang.org/firebase-7.0.0/lib/src/database.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
        allowInterop((update) => jsify(transactionUpdate(dartify(update))));
        ^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/firebase-7.0.0/lib/src/database.dart:166:26: Error: The method 'allowInterop' isn't defined for the class 'DatabaseReference<T>'.
 - 'DatabaseReference' is from 'package:firebase/src/database.dart' ('../../.pub-cache/hosted/pub.dartlang.org/firebase-7.0.0/lib/src/database.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
    var onCompleteWrap = allowInterop(
                         ^^^^^^^^^^^^

**Comment by kevmoo** [comment] 2019-12-03 00:39
Duplicate of https://github.com/FirebaseExtended/firebase-dart/issues/107

**Closed by kevmoo** 2019-12-03 00:39 UTC
